---
- name: Install sssd package
  package:
    name: "{{ sssd_pkg }}"
    state: present
  notify:
    - Restart sssd
  tags:
    - sssd_pkg

- name: Configure sssd service
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    mode: 0600
    owner: root
    group: root
  notify:
    - Restart sssd
  tags:
    - sssd_config

- include: service_module.yml
  when: not sssd_service_runit

- include: runit_module.yml
  when: sssd_service_runit
